{
  "timestamp": "2025-09-25T07:23:18.810209",
  "formatters": [
    {
      "name": "black",
      "rc": 1,
      "stdout": "",
      "stderr": "/home/user/DEVCoDE/@anyProjectTemplate/.venv/bin/python: No module named black\n"
    },
    {
      "name": "isort",
      "rc": 1,
      "stdout": "",
      "stderr": "/home/user/DEVCoDE/@anyProjectTemplate/.venv/bin/python: No module named isort\n"
    },
    {
      "name": "ruff",
      "rc": 1,
      "stdout": "",
      "stderr": "/home/user/DEVCoDE/@anyProjectTemplate/.venv/bin/python: No module named ruff\n"
    }
  ],
  "linters": [
    {
      "name": "flake8",
      "rc": 1,
      "stdout": "./scripts/ai_tools/auto_fix.py:7:89: E501 line too long (99 > 88 characters)\n./scripts/ai_tools/auto_fix.py:57:89: E501 line too long (91 > 88 characters)\n./scripts/ai_tools/auto_fix.py:76:89: E501 line too long (103 > 88 characters)\n./scripts/ai_tools/generator.py:38:89: E501 line too long (94 > 88 characters)\n./scripts/ai_tools/mcp_block.py:3:89: E501 line too long (139 > 88 characters)\n./scripts/ai_tools/reader.py:35:89: E501 line too long (98 > 88 characters)\n./scripts/ai_tools/reader.py:41:89: E501 line too long (90 > 88 characters)\n",
      "stderr": ""
    },
    {
      "name": "flake8",
      "rc": 1,
      "stdout": "./scripts/ai_tools/auto_fix.py:7:89: E501 line too long (99 > 88 characters)\n./scripts/ai_tools/auto_fix.py:57:89: E501 line too long (91 > 88 characters)\n./scripts/ai_tools/auto_fix.py:76:89: E501 line too long (103 > 88 characters)\n./scripts/ai_tools/generator.py:38:89: E501 line too long (94 > 88 characters)\n./scripts/ai_tools/mcp_block.py:3:89: E501 line too long (139 > 88 characters)\n./scripts/ai_tools/reader.py:35:89: E501 line too long (98 > 88 characters)\n./scripts/ai_tools/reader.py:41:89: E501 line too long (90 > 88 characters)\n",
      "stderr": ""
    }
  ],
  "tests": {
    "rc": 2,
    "stdout": "\n==================================== ERRORS ====================================\n_ ERROR collecting tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tests/test_tools.py _\nimport file mismatch:\nimported module 'test_tools' has this __file__ attribute:\n  /home/user/DEVCoDE/@anyProjectTemplate/tests/test_tools.py\nwhich is not the same as the test file we want to collect:\n  /home/user/DEVCoDE/@anyProjectTemplate/tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tests/test_tools.py\nHINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules\n_ ERROR collecting tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tests/test_tools.py _\nimport file mismatch:\nimported module 'test_tools' has this __file__ attribute:\n  /home/user/DEVCoDE/@anyProjectTemplate/tests/test_tools.py\nwhich is not the same as the test file we want to collect:\n  /home/user/DEVCoDE/@anyProjectTemplate/tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tests/test_tools.py\nHINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules\n=========================== short test summary info ============================\nERROR tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tests/test_tools.py\nERROR tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tmp/auto_fix/backups/2025-09-25T07:23:18.810283/tests/test_tools.py\n!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!\n2 errors in 0.13s\n",
    "stderr": ""
  },
  "backup_dir": "/home/user/DEVCoDE/@anyProjectTemplate/tmp/auto_fix/backups/2025-09-25T07:23:18.810283"
}